### ISSUE TITLE
System-generated constants disappear in termination condition

### ISSUE THREAD

**Issue by scmu** [scmlab/gcl#35] opened 2021-05-19 07:51 UTC
Given the test program:
```
con N : Int
con f : array [0..N) of Int
var n : Int

{ f[n] = 0, bnd: N - n }
do n ≠ N -> n := n + 1
od 
{ True } 
```
See the 2nd proof obligation for location `6:13-22`:

![Screen Shot 2021-05-19 at 3 45 03 PM](https://user-images.githubusercontent.com/11384501/118775482-913bad80-b8b9-11eb-892b-6392847fac05.jpg)

The system-generated constants are gone --- `N - n` should be `N - n = C` for some `C`, while `N - (n + 1)` should be `N - (n + 1) < C`.

**Comment by banacorn** [comment] 2021-05-19 09:25
Turned out to be an duplicate of #33

**Closed as completed by banacorn** 2021-05-19 09:25 UTC
Labels: bug, rendering
