### ISSUE TITLE
"Missing Postcondition" with presence of specs

### ISSUE THREAD

**Issue by scmu** [scmlab/gcl#15] opened 2021-03-12 14:54 UTC
I got an "Missing Postcondition" error even with the last statement (line 9) is an assertion. It seems that the error is triggered by the presence of the spec (line 5 - 7):
![Screen Shot 2021-03-12 at 10 47 34 PM](https://user-images.githubusercontent.com/11384501/110956264-6a2aa200-8385-11eb-821e-3f5ae857b091.jpg)

The error persists if I add a new line:
![Screen Shot 2021-03-12 at 10 48 04 PM](https://user-images.githubusercontent.com/11384501/110956281-6f87ec80-8385-11eb-8abd-29faae7ba593.jpg)

But if I indent line 8 by one more space (compare that with line 8 in the previous picture), the error is gone.
![Screen Shot 2021-03-12 at 10 48 12 PM](https://user-images.githubusercontent.com/11384501/110956300-731b7380-8385-11eb-8c6f-bf73ff889fef.jpg)

I guess that could be a parsing issue, so I reported the issue to gcl.

**Comment by scmu** [comment] 2021-03-12 15:05
Following up: in this situation, adding the space on line 10 does not resolve the error.
![Screen Shot 2021-03-12 at 11 04 31 PM](https://user-images.githubusercontent.com/11384501/110958167-5f710c80-8387-11eb-917d-bcbee9ad1ace.jpg)

**Comment by potsrevennil** [comment] 2021-03-14 17:05
I modified the indentation parsing rule for Spec and Proof.
If there is nothing in between the start and end token of Spec or Proof, it should parsed successfully.

However since the `Spec` and `Proof` constructor both only take start and end token as arguments,
e.g.
```
| Spec (Token "{!") (Token "!}")
| Proof (Token "{-") (Token "-}")
```
> Following up: in this situation, adding the space on line 10 does not resolve the error.
> ![Screen Shot 2021-03-12 at 11 04 31 PM](https://user-images.githubusercontent.com/11384501/110958167-5f710c80-8387-11eb-917d-bcbee9ad1ace.jpg)

the above issue might not be able to solve from parsing.

**Comment by scmu** [comment] 2021-03-14 17:34
> However since the `Spec` and `Proof` constructor both only take start and end token as arguments,
> e.g.
> 
> ```
> | Spec (Token "{!") (Token "!}")
> | Proof (Token "{-") (Token "-}")
> ```
....
> the above issue might not be able to solve from parsing.

Does that imply the spec and comments must always be empty? That should be an issue in itself.

I am opening another issue for it.

**Comment by potsrevennil** [comment] 2021-03-23 08:46
I think the issue is fixed now and pushed onto the branch lexer2.

**Closed as completed** 2021-04-14 07:39 UTC
Labels: parsing
